name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Start Tests
      id: start-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Start Tests
        setup-command: ''
        command: echo 'Start Tests'
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        START-TESTS_RESULTS: "${{steps.start-tests.outputs.result}}"
      with:
        runners: start-tests
